In [1]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
df_heladas = pd.read_excel('DISTRITOS_PRIORIZADOS-POR-HELADAS.xlsx')
df_friaje = pd.read_excel('DISTRITOS_PRIORIZADOS-POR-FRIAJE.xlsx')

In [37]:
def preprocess(df):
    header  = np.array(df.columns)
    header0 = np.array(df.iloc[0])
    header1 = np.array(df.iloc[1])
    header2 = np.array(df.iloc[2])
    columns = header2
    columns = [col1 if col1 == col1 else col2 for col1, col2 in zip(columns, header1)]
    columns = [col1 if col1 == col1 else col2 for col1, col2 in zip(columns, header0)]
    columns = [col1 if col1 == col1 else col2 for col1, col2 in zip(columns, header)]
    df = df.drop(df.index[0])
    df = df.drop(df.index[0])
    df = df.drop(df.index[0])
    df.columns = columns
    return df

In [38]:
df_heladas = preprocess(df_heladas)
df_friaje = preprocess(df_friaje)

In [39]:
df_heladas.head()

,Ubigeo distrital,Departamento,Provincia,Distrito,T° Mínima P10 (°C),Frecuencia de heladas (días/mes),Defunciones por neumonías (< a 5 años),Tasa de mortalidad (< a 5 años),Casos de neumonías (< a 5 años),Tasa de neumonías (< a 5 años),Valor del IDS,Incidencia de Pobreza,Tasa de Desnutrición Crónica (< a 5 años),Tasa de Analfabetismo,Porc. viviendas según el material utilizado para cocinar,Nivel de Riesgo MINSA,Total del distrito,Población menor a 5 años,Población de 60 años a más
3,010101,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,0 a 2,0 a 2 dias,0,0,21,10.6653,0.3158,12.27,14.6,3.53831,15.4818,MEDIO,28937,2036,2773
4,010102,AMAZONAS,CHACHAPOYAS,ASUNCION,0 a 2,0 a 2 dias,0,0,0,0,0.035,51.3,0,12.5926,96.4706,BAJO,288,24,45
5,010103,AMAZONAS,CHACHAPOYAS,BALSAS,-5 a 0,0 a 2 dias,0,0,1,5.68182,0.17,42.59,18.7,13.9423,91.7431,BAJO,1634,176,170
6,010104,AMAZONAS,CHACHAPOYAS,CHETO,0 a 2,0 a 2 dias,0,0,0,0,0.035,60.02,10.3,6.81818,91.4439,BAJO,591,50,67
7,010105,AMAZONAS,CHACHAPOYAS,CHILIQUIN,0 a 2,0 a 2 dias,0,0,0,0,0.035,74.73,22.5,11.9691,99.0244,MEDIO,698,63,90

In [40]:
df_friaje.head()

,Ubigeo distrital,Departamento,Provincia,Distrito,T° Mínima P5 (°C),Defunciones por neumonías (< a 5 años),Tasa de mortalidad (< a 5 años),Casos de neumonías (< a 5 años),Tasa de neumonías (< a 5 años),Valor del IDS,Incidencia de Pobreza,Tasa de Desnutrición Crónica (< a 5 años),Tasa de Analfabetismo,Porc. viviendas según el material utilizado para cocinar,Nivel de Riesgo MINSA,Total del distrito,Población menor a 5 años,Población de 60 años a más
3,010201,AMAZONAS,BAGUA,BAGUA,19°C a 20°C,0,0,10,4.77783,0.17,24.5219,11.6,5.89938,26.6215,MEDIO,26005,2091,2024
4,010202,AMAZONAS,BAGUA,ARAMANGO,19°C a 20°C,0,0,2,1.81324,0.0548,56.51,23.5,11.4329,85.7555,MEDIO,10969,1087,806
5,010204,AMAZONAS,BAGUA,EL PARCO,17°C a 19°C,0,0,0,0,0.035,48.43,24.5,11.3318,82.2981,MEDIO,1483,129,157
6,010205,AMAZONAS,BAGUA,IMAZA,19°C a 20°C,0,0,43,11.6468,0.3158,79.84,45.3,14.3448,92.4475,ALTO,24201,3677,959
7,010206,AMAZONAS,BAGUA,LA PECA,17°C a 19°C,0,0,2,3.10559,0.0944,63.19,14.1,12.8004,78.9474,ALTO,8019,619,804

In [41]:
len(df_heladas['Distrito'].unique())

1271

In [42]:
len(df_friaje['Distrito'].unique())

224

### Lectura de anexos

In [19]:
# tambos priorizados
df_tambos = pd.read_excel('Anexo 4.xlsx')

In [21]:
df_tambos.head()

,N°,Departamento,Provincia,Ubigeo distrital,Distrito,UBIG_TAM,UBIGEO_CCP,UBIGEO_DIS,DISTRITO,CCPP,LOCAL DE DISTRIBUCIÓN DE BIENES
0,1,PUNO,CARABAYA,210302,AJOYANI,2103050035,2103050035,210305,CORANI,AYMAÑA,TAMBO AYMAÑA
1,2,PUNO,CARABAYA,210305,CORANI,2103050035,2103050035,210305,CORANI,AYMAÑA,TAMBO AYMAÑA
2,3,PUNO,CARABAYA,210306,CRUCERO,2103050035,2103050035,210305,CORANI,AYMAÑA,TAMBO AYMAÑA
3,4,PUNO,CARABAYA,210301,MACUSANI,2103050035,2103050035,210305,CORANI,AYMAÑA,TAMBO AYMAÑA
4,5,PUNO,CARABAYA,210310,USICAYOS,2103050035,2103050035,210305,CORANI,AYMAÑA,TAMBO AYMAÑA

In [22]:
# zonas de intervencion
df_zonas = pd.read_excel('Anexo 2.xlsx')

In [23]:
df_zonas.head()

,N°,DEPARTAMENTO,PROVINCIA,DISTRITO,TAMBO/LOCAL PARA ENTREGA DE BIENES,FECHA DE ENTREGA
0,1,PUNO,AZANGARO,ACHAYA,LOCAL DISTRITAL AZANGARO,2017-04-25
1,2,PUNO,AZANGARO,ARAPA,LOCAL DISTRITAL AZANGARO,2017-04-25
2,3,PUNO,AZANGARO,ASILLO,LOCAL DISTRITAL AZANGARO,2017-04-25
3,4,PUNO,AZANGARO,AZANGARO,LOCAL DISTRITAL AZANGARO,2017-04-25
4,5,PUNO,AZANGARO,CAMINACA,LOCAL DISTRITAL AZANGARO,2017-04-25

In [25]:
len(df_tambos['Distrito'].unique())

115

In [26]:
len(df_zonas['DISTRITO'].unique())

237

In [29]:
len(set(df_tambos['Distrito'].unique()).intersection(df_zonas['DISTRITO'].unique()))

112

In [30]:
len(df_tambos['LOCAL DE DISTRIBUCIÓN DE BIENES'].unique())

55

In [46]:
len(set(df_tambos['Distrito'].unique()).intersection(set(df_heladas['Distrito']).union(df_friaje['Distrito'])))

108

In [47]:
len(set(df_zonas['DISTRITO'].unique()).intersection(set(df_heladas['Distrito']).union(df_friaje['Distrito'])))

230

In [55]:
set([" ".join([provincia, distrito]) for provincia, distrito in zip(df_heladas['Provincia'], df_heladas['Distrito'])]) \
    .intersection([" ".join([provincia, distrito]) for provincia, distrito in zip(df_friaje['Provincia'], df_friaje['Distrito'])])

set()

In [49]:
df_heladas[df_heladas['Distrito']=='BELEN']

,Ubigeo distrital,Departamento,Provincia,Distrito,T° Mínima P10 (°C),Frecuencia de heladas (días/mes),Defunciones por neumonías (< a 5 años),Tasa de mortalidad (< a 5 años),Casos de neumonías (< a 5 años),Tasa de neumonías (< a 5 años),Valor del IDS,Incidencia de Pobreza,Tasa de Desnutrición Crónica (< a 5 años),Tasa de Analfabetismo,Porc. viviendas según el material utilizado para cocinar,Nivel de Riesgo MINSA,Total del distrito,Población menor a 5 años,Población de 60 años a más
483,050902,AYACUCHO,SUCRE,BELEN,-5 a 0,2 a 5 dias,0,0,0,0,0.035,55.09,28.6,19.8198,90.566,MEDIO,759,65,125

In [50]:
df_friaje[df_friaje['Distrito']=='BELEN']

,Ubigeo distrital,Departamento,Provincia,Distrito,T° Mínima P5 (°C),Defunciones por neumonías (< a 5 años),Tasa de mortalidad (< a 5 años),Casos de neumonías (< a 5 años),Tasa de neumonías (< a 5 años),Valor del IDS,Incidencia de Pobreza,Tasa de Desnutrición Crónica (< a 5 años),Tasa de Analfabetismo,Porc. viviendas según el material utilizado para cocinar,Nivel de Riesgo MINSA,Total del distrito,Población menor a 5 años,Población de 60 años a más
75,160112,LORETO,MAYNAS,BELEN,19°C a 20°C,1,0.135446,24,3.25071,0.1076,33.32,22.7,3.29293,57.1823,MEDIO,76342,7323,5689

### Begin merge

**Replace line break symbols:**

In [83]:
df_tambos['Departamento'] = df_tambos['Departamento'].apply(lambda x: x.replace('\n', ' '))
df_tambos['Provincia'] = df_tambos['Provincia'].apply(lambda x: x.replace('\n', ' '))
df_tambos['Distrito'] = df_tambos['Distrito'].apply(lambda x: x.replace('\n', ' '))

In [84]:
df_heladas['Departamento'] = df_heladas['Departamento'].apply(lambda x: x.replace('\n', ' '))
df_heladas['Provincia'] = df_heladas['Provincia'].apply(lambda x: x.replace('\n', ' '))
df_heladas['Distrito'] = df_heladas['Distrito'].apply(lambda x: x.replace('\n', ' '))

In [89]:
df_friaje['Departamento'] = df_friaje['Departamento'].apply(lambda x: x.replace('\n', ' '))
df_friaje['Provincia'] = df_friaje['Provincia'].apply(lambda x: x.replace('\n', ' '))
df_friaje['Distrito'] = df_friaje['Distrito'].apply(lambda x: x.replace('\n', ' '))

**Concat df_heladas and df_friaje:**

In [102]:
set(df_heladas.columns).symmetric_difference(df_friaje.columns)

{'Frecuencia de heladas (días/mes)',
 'T° Mínima P10 (°C)',
 'T° Mínima P5\n (°C)'}

In [95]:
df_heladas.shape, df_friaje.shape

((1371, 19), (229, 18))

In [103]:
df_heladas.append(df_friaje).shape

(1600, 20)

In [114]:
df = pd.merge(df_tambos, df_heladas.append(df_friaje), how='left', on=['Departamento', 'Provincia', 'Distrito'])

In [115]:
df.to_csv('merge.csv', index=False)

**Drop nan rows:**

In [116]:
df[df['Total del distrito'].isnull()]

,N°,Departamento,Provincia,Ubigeo distrital_x,Distrito,UBIG_TAM,UBIGEO_CCP,UBIGEO_DIS,DISTRITO,CCPP,...,Porc. viviendas según el material utilizado para cocinar,Tasa de Analfabetismo,Tasa de Desnutrición Crónica (< a 5 años),Tasa de mortalidad (< a 5 años),Tasa de neumonías (< a 5 años),Total del distrito,T° Mínima P10 (°C),T° Mínima P5 (°C),Ubigeo distrital_y,Valor del IDS
30,31,PUNO,MELGAR,210806,NUÑOA,2108060063,2108060063,210806,NUÑOA,ANANSAYA PUNA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,58,AYACUCHO,SUCRE,50905,HUACAÑA,509050015,509050015,50905,HUACAÑA,ALUZPAMPA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,78,CUSCO,CHUMBIVILCAS,80707,QUIÑOTA,807050031,807050031,80705,LIVITACA,QQUECHAQUEHUINCHA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,102,HUANUCO,HUAMALIES,100509,PUÑOS,1005090060,1005090060,100509,PUÑOS,SAGSHACANCHA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [117]:
df.shape

(117, 28)

In [118]:
df = df.dropna(axis=0, subset=['Total del distrito'])
df.shape

(113, 28)

In [119]:
df.to_csv('merge.csv')

### Checkpoint

In [120]:
import requests

In [124]:
row = df.loc[0]
address = ','.join([row['Distrito'].replace(' ','+'), row['Provincia'].replace(' ','+'), row['Departamento'].replace(' ','+')])
address

'AJOYANI,CARABAYA,PUNO'

In [125]:
API_KEY = 'AIzaSyACxnslQpjPX-qN6wIinlY7r1k9DUiS1vs'
response = requests.get('https://maps.googleapis.com/maps/api/geocode/json?address={}&key={}' \
             .format(address, API_KEY))

In [141]:
response.json()

{'results': [{'address_components': [{'long_name': 'Ajoyani',
     'short_name': 'Ajoyani',
     'types': ['locality', 'political']},
    {'long_name': 'Carabaya',
     'short_name': 'Carabaya',
     'types': ['administrative_area_level_2', 'political']},
    {'long_name': 'Puno',
     'short_name': 'Puno',
     'types': ['administrative_area_level_1', 'political']},
    {'long_name': 'Peru',
     'short_name': 'PE',
     'types': ['country', 'political']}],
   'formatted_address': 'Ajoyani, Peru',
   'geometry': {'location': {'lat': -14.1, 'lng': -70.2},
    'location_type': 'APPROXIMATE',
    'viewport': {'northeast': {'lat': -14.0891779, 'lng': -70.1839926},
     'southwest': {'lat': -14.1108216, 'lng': -70.2160074}}},
   'place_id': 'ChIJQ_m9zXvjZZERoynRfs5kJvg',
   'types': ['locality', 'political']}],
 'status': 'OK'}

In [154]:
response.json()['status']

'OK'

In [155]:
row['N°']

1

In [139]:
location = response.json()['results'][0]['geometry']['location']
location['lat'], location['lng']

(-14.1, -70.2)

In [144]:
df.head()

,N°,Departamento,Provincia,Ubigeo distrital_x,Distrito,UBIG_TAM,UBIGEO_CCP,UBIGEO_DIS,DISTRITO,CCPP,...,Tasa de Desnutrición Crónica (< a 5 años),Tasa de mortalidad (< a 5 años),Tasa de neumonías (< a 5 años),Total del distrito,T° Mínima P10 (°C),T° Mínima P5 (°C),Ubigeo distrital_y,Valor del IDS,Latitud,Longitud
0,1,PUNO,CARABAYA,210302,AJOYANI,2103050035,2103050035,210305,CORANI,AYMAÑA,...,27.3,0,0,2099,-14 a -11,NaN,210302,0.035,None,None
1,2,PUNO,CARABAYA,210305,CORANI,2103050035,2103050035,210305,CORANI,AYMAÑA,...,49.3,0,0,3956,-20 a -14,NaN,210305,0.035,None,None
2,3,PUNO,CARABAYA,210306,CRUCERO,2103050035,2103050035,210305,CORANI,AYMAÑA,...,34.6,0,0,9306,-20 a -14,NaN,210306,0.035,None,None
3,4,PUNO,CARABAYA,210301,MACUSANI,2103050035,2103050035,210305,CORANI,AYMAÑA,...,35.4,0.547645,19.1676,13015,-14 a -11,NaN,210301,0.3554,None,None
4,5,PUNO,CARABAYA,210310,USICAYOS,2103050035,2103050035,210305,CORANI,AYMAÑA,...,41.1,0,0,23937,-14 a -11,NaN,210310,0.035,None,None

In [170]:
df['Latitud'] = None
df['Longitud'] = None

In [201]:
leback = response_backup[:]

In [202]:
backup = []
response_backup = []

In [205]:
API_KEY = 'AIzaSyACxnslQpjPX-qN6wIinlY7r1k9DUiS1vs'

def foo(row):
    global backup
    global response_backup
    address = ','.join([row['Distrito'].replace(' ','+'), row['Provincia'].replace(' ','+'), row['Departamento'].replace(' ','+')])
    response = requests.get('https://maps.googleapis.com/maps/api/geocode/json?address={}&key={}'.format(address, API_KEY))
    response_backup += [response]
    location = {'lat': None, 'lng': None}
    try:
        location = response.json()['results'][0]['geometry']['location']
    except:
        print('Exception at: ', row['N°'], response.json()['status'])
    row['Latitud'] = location['lat']
    row['Longitud'] = location['lng']
    backup += [row]
    print(row['N°'], response.json()['status'])
    return row

df2 = df.apply(foo, axis=1)

1 OK
1 OK
2 OK
3 OK
4 OK
5 OK
6 OK
7 OK
8 OK
9 OK
Exception at:  10 ZERO_RESULTS
10 ZERO_RESULTS
11 OK
12 OK
13 OK
14 OK
15 OK
16 OK
17 OK
18 OK
19 OK
20 OK
21 OK
22 OK
23 OK
24 OK
25 OK
26 OK
27 OK
28 OK
29 OK
30 OK
32 OK
33 OK
34 OK
Exception at:  35 ZERO_RESULTS
35 ZERO_RESULTS
36 OK
37 OK
38 OK
39 OK
Exception at:  40 ZERO_RESULTS
40 ZERO_RESULTS
41 OK
42 OK
43 OK
44 OK
45 OK
46 OK
47 OK
48 OK
49 OK
50 OK
51 OK
52 OK
53 OK
54 OK
55 OK
56 OK
57 OK
59 OK
60 OK
61 OK
Exception at:  62 ZERO_RESULTS
62 ZERO_RESULTS
63 OK
64 OK
65 OK
66 OK
67 OK
68 OK
69 OK
70 OK
71 OK
72 OK
73 OK
74 OK
75 OK
76 OK
77 OK
79 OK
80 OK
Exception at:  81 ZERO_RESULTS
81 ZERO_RESULTS
82 OK
83 OK
84 OK
Exception at:  85 ZERO_RESULTS
85 ZERO_RESULTS
86 OK
87 OK
88 OK
89 OK
90 OK
91 OK
92 OK
93 OK
94 OK
95 OK
96 OK
97 OK
98 OK
99 OK
100 OK
101 OK
103 OK
104 OK
105 OK
105 OK
106 OK
107 OK
108 OK
109 OK
110 OK
111 OK
112 OK
113 OK
114 OK
115 OK
116 OK

In [206]:
df2.head()

,N°,Departamento,Provincia,Ubigeo distrital_x,Distrito,UBIG_TAM,UBIGEO_CCP,UBIGEO_DIS,DISTRITO,CCPP,...,Tasa de Desnutrición Crónica (< a 5 años),Tasa de mortalidad (< a 5 años),Tasa de neumonías (< a 5 años),Total del distrito,T° Mínima P10 (°C),T° Mínima P5 (°C),Ubigeo distrital_y,Valor del IDS,Latitud,Longitud
0,1,PUNO,CARABAYA,210302,AJOYANI,2103050035,2103050035,210305,CORANI,AYMAÑA,...,27.3,0.000000,0.000000,2099,-14 a -11,NaN,210302,0.0350,-14.100000,-70.200000
1,2,PUNO,CARABAYA,210305,CORANI,2103050035,2103050035,210305,CORANI,AYMAÑA,...,49.3,0.000000,0.000000,3956,-20 a -14,NaN,210305,0.0350,-13.889910,-70.647842
2,3,PUNO,CARABAYA,210306,CRUCERO,2103050035,2103050035,210305,CORANI,AYMAÑA,...,34.6,0.000000,0.000000,9306,-20 a -14,NaN,210306,0.0350,-14.345380,-70.032097
3,4,PUNO,CARABAYA,210301,MACUSANI,2103050035,2103050035,210305,CORANI,AYMAÑA,...,35.4,0.547645,19.167579,13015,-14 a -11,NaN,210301,0.3554,-14.072176,-70.425339
4,5,PUNO,CARABAYA,210310,USICAYOS,2103050035,2103050035,210305,CORANI,AYMAÑA,...,41.1,0.000000,0.000000,23937,-14 a -11,NaN,210310,0.0350,-14.125468,-69.966159

In [207]:
df2[df2['Latitud'].isnull()]

,N°,Departamento,Provincia,Ubigeo distrital_x,Distrito,UBIG_TAM,UBIGEO_CCP,UBIGEO_DIS,DISTRITO,CCPP,...,Tasa de Desnutrición Crónica (< a 5 años),Tasa de mortalidad (< a 5 años),Tasa de neumonías (< a 5 años),Total del distrito,T° Mínima P10 (°C),T° Mínima P5 (°C),Ubigeo distrital_y,Valor del IDS,Latitud,Longitud
9,10,PUNO,EL COLLAO,210502,CAPAZO,2105020001,2105020001,210502,CAPAZO,CAPAZO,...,18.2,0.0,0.0,2265,-20 a -14,NaN,210502,0.035,NaN,NaN
34,35,PUNO,SAN ANTONIO DE PUTINA,211003,PEDRO VILCA APAZA,2110030001,2110030001,211003,PEDRO VILCA\nAPAZA,AYRAMPUNI,...,17.7,0.0,0.0,2978,-14 a -11,NaN,211003,0.035,NaN,NaN
39,40,APURIMAC,ANTABAMBA,30304,JUAN ESPINOZA MEDRANO,303040016,303040016,30304,JUAN ESPINOZA\nMEDRANO,CALCAUSO,...,35.4,0.0,0.0,2049,-14 a -11,NaN,030304,0.035,NaN,NaN
61,62,CUSCO,CANAS,80503,KUNTURKANKI,805030005,805030005,80503,KUNTURKANKI,PUMATHALLA,...,31.0,0.0,0.0,5745,-14 a -11,NaN,080503,0.035,NaN,NaN
80,81,CUSCO,ESPINAR,80808,ALTO PICHIGUA,808030019,808030019,80803,COPORAQUE,SANTA ROSA\nHUAYHUASI,...,32.2,0.0,0.0,3147,-14 a -11,NaN,080808,0.035,NaN,NaN
84,85,CUSCO,ESPINAR,80804,OCORURO,808070083,808070083,80807,SUYCKUTAMBO,ESCALERA,...,31.3,0.0,0.0,1593,-14 a -11,NaN,080804,0.035,NaN,NaN

In [208]:
df2.to_csv('latitud+longitud.csv', index=False)

In [210]:
df2.loc['']

9     2265
34    2978
39    2049
61    5745
80    3147
84    1593
Name: Total del distrito, dtype: int64

In [217]:
import json
with open('response_log.json', 'w') as outfile:
    json.dump([response.json() for response in response_backup], outfile)

### Latitude and longitude Checkpoint

In [4]:
df = pd.read_csv('latitud+longitud.csv', encoding='latin-1')

In [5]:
df.head()

,N°,Departamento,Provincia,Ubigeo distrital_x,Distrito,UBIG_TAM,UBIGEO_CCP,UBIGEO_DIS,DISTRITO,CCPP,...,Tasa de Desnutrición Crónica (< a 5 años),Tasa de mortalidad (< a 5 años),Tasa de neumonías (< a 5 años),Total del distrito,T° Mínima P10 (°C),T° Mínima P5 (°C),Ubigeo distrital_y,Valor del IDS,Latitud,Longitud
0,1,PUNO,CARABAYA,210302,AJOYANI,2103050035,2103050035,210305,CORANI,AYMAÑA,...,27.3,0.000000,0.000000,2099,-14 a -11,NaN,210302,0.0350,-14.100000,-70.200000
1,2,PUNO,CARABAYA,210305,CORANI,2103050035,2103050035,210305,CORANI,AYMAÑA,...,49.3,0.000000,0.000000,3956,-20 a -14,NaN,210305,0.0350,-13.889910,-70.647842
2,3,PUNO,CARABAYA,210306,CRUCERO,2103050035,2103050035,210305,CORANI,AYMAÑA,...,34.6,0.000000,0.000000,9306,-20 a -14,NaN,210306,0.0350,-14.345380,-70.032097
3,4,PUNO,CARABAYA,210301,MACUSANI,2103050035,2103050035,210305,CORANI,AYMAÑA,...,35.4,0.547645,19.167579,13015,-14 a -11,NaN,210301,0.3554,-14.072176,-70.425339
4,5,PUNO,CARABAYA,210310,USICAYOS,2103050035,2103050035,210305,CORANI,AYMAÑA,...,41.1,0.000000,0.000000,23937,-14 a -11,NaN,210310,0.0350,-14.125468,-69.966159

In [7]:
df.shape

(113, 30)

 <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css"
   integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ=="
   crossorigin=""/>
   
 <!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"
   integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log=="
   crossorigin=""></script>
 
 <head>
<style>
    #mapid { height: 180px; }
</style>
</head>
 
 <div id="mapid"></div>